Vagrant.configure("2") do |config|

  config.vm.box_check_update = false

  # =========================
  # WEB SERVER
  # =========================
  config.vm.define "web" do |web|

    web.vm.box = "ubuntu/jammy64"
    web.vm.hostname = "wordpress-web"

    web.vm.network "private_network",
      ip: "192.168.56.10"

    web.vm.provider "virtualbox" do |vb|
      vb.name = "WordPress-Web"
      vb.memory = 2048
      vb.cpus = 2
    end

    web.vm.provision "shell",
      path: "web.sh"

  end

  # =========================
  # DATABASE SERVER
  # =========================
  config.vm.define "db" do |db|

    db.vm.box = "ubuntu/jammy64"
    db.vm.hostname = "wordpress-db"

    db.vm.network "private_network",
      ip: "192.168.56.20"

    db.vm.provider "virtualbox" do |vb|
      vb.name = "WordPress-Database"
      vb.memory = 2048
      vb.cpus = 2
    end

    db.vm.provision "shell",
      path: "db.sh"

  end

end
